on:
  push:
    branches:
      - content

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: publish
        run: cd hacken.fun && make github